### PR TITLE
Convert to styled components

### PR DESCRIPTION
**Pull request by leerssej**
✅ converts all inline style components to styled-components
✅ adds conditional formatting for `Exclusions` subcomponent.
✅ adds conditional formatting for secondary address record in location space
☑️ establishing a viable Jest and Enzyme environment (even in testing environments) has proved challenging.

### CODE REVIEW

**Review by alecHyde — APPROVED** [review]
I haven't seen this version of inline CSS formatting before, but looks good!

**Comment by leerssej** [comment]
This style seems to be the elusive styled components: https://codeburst.io/4-four-ways-to-style-react-components-ac6f323da822
I am glad I did it the inline way first, even if it was a bit of work swapping the formats back out. 
That way I only had to do one thing at a time. Deciding on component chunks straight off (instead of choosing from an html element first) seems like it might have been a bit more challenging to handle all at once.

**Comment by leerssej** [comment]
[convert inline styling to styled-components](https://trello.com/c/pNVVkRf7/37-convert-inline-styling-to-styled-components)

**Comment by leerssej** [comment]
[convert inline styling to styled-components](https://trello.com/c/pNVVkRf7/37-convert-inline-styling-to-styled-components)

**Pull request merged**
