### PR TITLE
updates readme

### PR DESCRIPTION
**Pull request by leerssej**

### CODE REVIEW

**Review by Nolsky — APPROVED** [review]
I approve of these changes

**Review by alecHyde — COMMENTED** [review]
Looks good to me

**Review by christian-r-n — CHANGES_REQUESTED** [review]
Looks great. Are you going to add the Airbnb eslinter?

**Comment by leerssej** [comment]
airbnb eslinter added and passed preliminary tests

**Review by christian-r-n — APPROVED** [review]
Great! Thanks.

**Pull request merged**
