### PR TITLE
Connect state to descrip database

### PR DESCRIPTION
**Pull request by leerssej**
✅ connects page with API using axios.
✅ renders all description components in page.
✅ renders components in appropriate styles (mostly).
  ☑️ uses _inline styling_  - see here for more info:https://codeburst.io/4-four-ways-to-style-react-components-ac6f323da822 
  ☑️ good first step for developing the more abstracted _styled-components_.

### CODE REVIEW

**Review by Nolsky — APPROVED** [review]
Looks good, I like the ES6 refactoringm in the webpack file.

**Comment by leerssej** [comment]
Thanks!
I can thank the linter for its nudging on many points. The modern style it helps encourage certainly feels much cleaner and smoother. 🙂

**Comment by leerssej** [comment]
[convert inline styling to styled-components](https://trello.com/c/pNVVkRf7/37-convert-inline-styling-to-styled-components)

**Comment by leerssej** [comment]
[Pulling dynamic data into front-end and swapping it in for the hardcoded data.](https://trello.com/c/2PPIVoYC/26-pulling-dynamic-data-into-front-end-and-swapping-it-in-for-the-hardcoded-data)

**Pull request merged**
